### PR TITLE
[WIP] Add distro boot support

### PR DESCRIPTION
**Pull request by kwizart**
This is a WIP of the distro boot support as reported in issue#24

Currently working up to defining a good ramdisk_addr_r value.

Signed-off-by: Nicolas Chauvet <kwizart@gmail.com>

### CODE REVIEW

**Comment by xc-racer99** [comment]
Hmm, looking good.

A couple of questions:
- Once you've run the bootcmd for the mmc, does it then ask which partition/kernel to boot from if you've set up multiple?
- Can you post the extlinux.conf file you're using?  I'd be curious to see an actual working example
- Do we need to hardcode the mmc booting entries or can we dynamically add them to the bootmenu, ie something like
```
if (env_get("bootcmd_mmc0") != NULL)
```
- How well does it handle injecting bootargs, like the MTD layout and UBI partition?  I suppose it would also be possible to specify this in the DTB.  This is needed for access to the EFS and modem partitions from linux.
- I'd like to try and get Android booting from a u-boot.scr file stored on a UBIFS partition on the onenand.  If you could give me a heads up when you think I should try adding this please let me know!

Edit: Just read your comment in #24 - I can add the UBI info as I have a booting Android install once you're happy with the MMC part of things.  With the ramdisk address, I'm surprised it doesn't work as there's still 16MB of ram past there.  You could try putting it at 0x40000000 as then you have a full 256MB to play with.

**Comment by kwizart** [comment]
* bootcmd_mmc0 will autodetect the appropriate boot partition to use with scan_dev_for_boot_part. First found  will match I would say. If there are multiple boot partitions . it should be possible to override the scan_dev_for_boot_part function to pass the appropriate one.

* Here is the full extlinux.conf file I'm using. Of course only the first entry could eventually work since Fedora doesn't yet enable support for the soc (if it can have multi-platform support).
```
# extlinux.conf generated by appliance-creator
ui menu.c32
menu autoboot Welcome to Fedora-Xfce-armhfp-Rawhide-20190121.n.1. Automatic boot in # second{,s}. Press a key for options.
menu title Fedora-Xfce-armhfp-Rawhide-20190121.n.1 Boot Options.
menu hidden
timeout 20
totaltimeout 600

label Fedora-30
        kernel /boot/zImage
        append ro root=bd578d2e-1e02-41a8-8863-24d97486fa27 LANG=fr_FR.UTF-8 cma=64MB
        fdtdir /boot
        initrd /boot/initramfs-5.0.0-0.rc3.git0.1.fc30.armv7hl.img

label Fedora-Xfce-armhfp-Rawhide-20190121.n.1 (5.0.0-0.rc3.git0.1.fc30.armv7hl)
        kernel /boot/vmlinuz-5.0.0-0.rc3.git0.1.fc30.armv7hl
        append ro root=bd578d2e-1e02-41a8-8863-24d97486fa27 LANG=fr_FR.UTF-8 cma=64MB
        fdtdir /boot/dtb-5.0.0-0.rc3.git0.1.fc30.armv7hl/
        initrd /boot/initramfs-5.0.0-0.rc3.git0.1.fc30.armv7hl.img
```

* I don't know if it can be autodetected or should we assume a per-board/soc partition layout as a convention.
* Once the ubifs support is sorted out, I think the idea would be for it to scan for extlinux.conf support first, then fallback to boot.scr automatically. By default it searches bootubipart and bootubivol can be used to control which partititon it should look at.

I will try to the new ramdisk address. The default initramfs in fedora is huge given it's a generic one, it can be reduced later...

EDIT: no luck with ramdisk address, I will open a separate ticket to sort that issue.

**Comment by PabloPL** [comment]
@kwizart This PR can be now closed?

**Comment by xc-racer99** [comment]
Yep, this one can be closed, everything from it has been merged in #29 

Thanks @kwizart for getting the ball rolling on this and for testing!

**Pull request closed without merging**
