### PR TITLE
U boot update

### PR DESCRIPTION
**Pull request by xc-racer99**
Only supports updating from first partition on SD card and only when the first three blocks in the u-boot partition aren't bad

### CODE REVIEW

**Comment by PabloPL** [comment]
Looks good for me. Couldn't update uboot because got message that OneNAND contains bad block and i need to use Odin/Heimdall (but if it works for others, lets merge it).

**Review by PabloPL — APPROVED** [review]

**Comment by xc-racer99** [comment]
What does "onenand bad" show?
It could be the "fake" bad blocks caused by an earlier failed version - try flashing a larger file (at least 1MB) via Odin/Heimdall, then reflashing u-boot.bin as Heimdall will clear the bad blocks if they're not factory bad blocks.

**Comment by PabloPL** [comment]
Sorry, it's now working fine - it looks like there were some changes on remote branch which i didn't had.

Ready to merge!

**Comment by PabloPL** [comment]
```
OneNAND checkbad: offset 0x1200000, size 0xc0000
Testing block 72 at 0x1200000
Testing block 73 at 0x1240000
Testing block 74 at 0x1280000
No bad blocks

OneNAND erase: offset 0x1200000, size 0xc0000
OK

OneNAND write: offset 0x1200000, size 0xc0000
 786432 bytes written: OK
Success!
```

**Pull request merged**
